/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Nov 11 09:38:55 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.sysmanager;

import java.io.Serializable;

/**
 * A class that represents a row in the StorageID table. 
 * You can customize the behavior of this class by editing the class, {@link Storageid()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractStorageid 
    implements Serializable
{

    /** The value of the comid association. */
    private java.lang.String comid;

    /** The value of the loginuserSet one-to-many association. */
    private java.util.Set loginuserSet;

    /** The value of the simple storageid property. */
    private java.lang.String storageid;

    /** The value of the simple storagename property. */
    private java.lang.String storagename;

    /** The value of the simple parentstorageid property. */
    private java.lang.String parentstorageid;

    /** The value of the simple storagehead property. */
    private java.lang.String storagehead;
    
    /** The value of the simple storagetype property. */
    private java.lang.String storagetype;

    /** The value of the simple phone property. */
    private java.lang.String phone;

    /** The value of the simple fax property. */
    private java.lang.String fax;

    /** The value of the simple email property. */
    private java.lang.String email;

    /** The value of the simple enabledflag property. */
    private java.lang.String enabledflag;

    /** The value of the simple rem property. */
    private java.lang.String rem;

    /**
     * Simple constructor of AbstractStorageid instances.
     */
    public AbstractStorageid()
    {
    }

    /**
     * Return the value of the StorageID column.
     * @return java.lang.String
     */
    public java.lang.String getStorageid()
    {
        return this.storageid;
    }

    /**
     * Set the value of the StorageID column.
     * @param storageid
     */
    public void setStorageid(java.lang.String storageid)
    {
        this.storageid = storageid;
    }

    /**
     * Return the value of the StorageName column.
     * @return java.lang.String
     */
    public java.lang.String getStoragename()
    {
        return this.storagename;
    }

    /**
     * Set the value of the StorageName column.
     * @param storagename
     */
    public void setStoragename(java.lang.String storagename)
    {
        this.storagename = storagename;
    }

    /**
     * Return the value of the ComID column.
     * @return Company
     */
    public java.lang.String getComid()
    {
        return this.comid;
    }

    /**
     * Set the value of the ComID column.
     * @param company
     */
    public void setComid(java.lang.String comid)
    {
        this.comid = comid;
    }

    /**
     * Return the value of the ParentStorageID column.
     * @return java.lang.String
     */
    public java.lang.String getParentstorageid()
    {
        return this.parentstorageid;
    }

    /**
     * Set the value of the ParentStorageID column.
     * @param parentstorageid
     */
    public void setParentstorageid(java.lang.String parentstorageid)
    {
        this.parentstorageid = parentstorageid;
    }

    /**
     * Return the value of the StorageHead column.
     * @return java.lang.String
     */
    public java.lang.String getStoragehead()
    {
        return this.storagehead;
    }

    /**
     * Set the value of the StorageHead column.
     * @param storagehead
     */
    public void setStoragehead(java.lang.String storagehead)
    {
        this.storagehead = storagehead;
    }
    
    /**
     * Return the value of the Storagetype column.
     * @return java.lang.String
     */
    public java.lang.String getStoragetype()
    {
        return this.storagetype;
    }

    /**
     * Set the value of the Storagetype column.
     * @param storagetype
     */
    public void setStoragetype(java.lang.String storagetype)
    {
        this.storagetype = storagetype;
    }

    /**
     * Return the value of the Phone column.
     * @return java.lang.String
     */
    public java.lang.String getPhone()
    {
        return this.phone;
    }

    /**
     * Set the value of the Phone column.
     * @param phone
     */
    public void setPhone(java.lang.String phone)
    {
        this.phone = phone;
    }

    /**
     * Return the value of the Fax column.
     * @return java.lang.String
     */
    public java.lang.String getFax()
    {
        return this.fax;
    }

    /**
     * Set the value of the Fax column.
     * @param fax
     */
    public void setFax(java.lang.String fax)
    {
        this.fax = fax;
    }

    /**
     * Return the value of the Email column.
     * @return java.lang.String
     */
    public java.lang.String getEmail()
    {
        return this.email;
    }

    /**
     * Set the value of the Email column.
     * @param email
     */
    public void setEmail(java.lang.String email)
    {
        this.email = email;
    }

    /**
     * Return the value of the EnabledFlag column.
     * @return java.lang.String
     */
    public java.lang.String getEnabledflag()
    {
        return this.enabledflag;
    }

    /**
     * Set the value of the EnabledFlag column.
     * @param enabledflag
     */
    public void setEnabledflag(java.lang.String enabledflag)
    {
        this.enabledflag = enabledflag;
    }

    /**
     * Return the value of the Rem column.
     * @return java.lang.String
     */
    public java.lang.String getRem()
    {
        return this.rem;
    }

    /**
     * Set the value of the Rem column.
     * @param rem
     */
    public void setRem(java.lang.String rem)
    {
        this.rem = rem;
    }

    /**
     * Return the value of the StorageID collection.
     * @return Loginuser
     */
    public java.util.Set getLoginuserSet()
    {
        return this.loginuserSet;
    }

    /**
     * Set the value of the StorageID collection.
     * @param loginuserSet
     */
    public void setLoginuserSet(java.util.Set loginuserSet)
    {
        this.loginuserSet = loginuserSet;
    }
}
