/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Oct 21 13:28:59 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.sysmanager;

import java.io.Serializable;

/**
 * A class that represents a row in the GetNum table. 
 * You can customize the behavior of this class by editing the class, {@link Getnum()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractGetnum 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The simple primary key value. */
    private GetnumKey id;

    /** The value of the simple nextno property. */
    private java.lang.Integer nextno;

    /**
     * Simple constructor of AbstractGetnum instances.
     */
    public AbstractGetnum()
    {
    }

    /**
     * Constructor of AbstractGetnum instances given a composite primary key.
     * @param id
     */
    public AbstractGetnum(GetnumKey id)
    {
        this.setId(id);
    }

    /**
     * Return the composite id instance that identifies this object.
     * @return GetnumKey
     */
    public GetnumKey getId()
    {
        return this.id;
    }

    /**
     * Set the composite id instance that identifies this object.
     * @param id
     */
    public void setId(GetnumKey id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the NextNO column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getNextno()
    {
        return this.nextno;
    }

    /**
     * Set the value of the NextNO column.
     * @param nextno
     */
    public void setNextno(java.lang.Integer nextno)
    {
        this.nextno = nextno;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Getnum))
            return false;
        Getnum that = (Getnum) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            if (this.getId() == null)
            {
                result = super.hashCode();
            }
            else
            {
                result = this.getId().hashCode();
            }
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
