/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Sat Nov 05 17:04:28 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.sysmanager;

import java.io.Serializable;

/**
 * A class that represents a row in the LoginUser table. 
 * You can customize the behavior of this class by editing the class, {@link Loginuser()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractLoginuser 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.String userid;

    /** The value of the role association. */
    private java.lang.String roleid;

    /** The value of the unitinfo association. */
    private java.lang.String storageid;
    
    /** The value of the dutyid association. */
    private java.lang.String class1id;
    
    /** The value of the dutyid association. */
    private java.lang.String dutyid;

    /** The value of the operref association. */
    private java.lang.String operref;
   
    /** The value of the simple username property. */
    private java.lang.String username;

    /** The value of the simple passwd property. */
    private java.lang.String passwd;

    /** The value of the simple phone property. */
    private java.lang.String phone;

    /** The value of the simple fax property. */
    private java.lang.String fax;

    /** The value of the simple email property. */
    private java.lang.String email;

    /** The value of the simple enabledflag property. */
    private java.lang.String enabledflag;

    /** The value of the simple rem1 property. */
    private java.lang.String rem1;
 
    private String grcid;
    private String idcardno;
    private String phoneimei;
    
    private String newphone;
    private String newemail;
    private String nweidcardno;
    private String auditoperid;
    private String auditdate;
    private String auditrem;
    
    public String getNewphone() {
		return newphone;
	}

	public void setNewphone(String newphone) {
		this.newphone = newphone;
	}

	public String getNewemail() {
		return newemail;
	}

	public void setNewemail(String newemail) {
		this.newemail = newemail;
	}

	public String getNweidcardno() {
		return nweidcardno;
	}

	public void setNweidcardno(String nweidcardno) {
		this.nweidcardno = nweidcardno;
	}

	public String getAuditoperid() {
		return auditoperid;
	}

	public void setAuditoperid(String auditoperid) {
		this.auditoperid = auditoperid;
	}

	public String getAuditdate() {
		return auditdate;
	}

	public void setAuditdate(String auditdate) {
		this.auditdate = auditdate;
	}

	public String getAuditrem() {
		return auditrem;
	}

	public void setAuditrem(String auditrem) {
		this.auditrem = auditrem;
	}

	public String getPhoneimei() {
		return phoneimei;
	}

	public void setPhoneimei(String phoneimei) {
		this.phoneimei = phoneimei;
	}

	public String getIdcardno() {
		return idcardno;
	}

	public void setIdcardno(String idcardno) {
		this.idcardno = idcardno;
	}

	/**
     * Simple constructor of AbstractLoginuser instances.
     */
    public AbstractLoginuser()
    {
    }

    /**
     * Constructor of AbstractLoginuser instances given a simple primary key.
     * @param userid
     */
    public AbstractLoginuser(java.lang.String userid)
    {
        this.setUserid(userid);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.String
     */
    public java.lang.String getUserid()
    {
        return userid;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param userid
     */
    public void setUserid(java.lang.String userid)
    {
        this.hashValue = 0;
        this.userid = userid;
    }

    /**
     * Return the value of the UserName column.
     * @return java.lang.String
     */
    public java.lang.String getUsername()
    {
        return this.username;
    }

    /**
     * Set the value of the UserName column.
     * @param username
     */
    public void setUsername(java.lang.String username)
    {
        this.username = username;
    }

    /**
     * Return the value of the Passwd column.
     * @return java.lang.String
     */
    public java.lang.String getPasswd()
    {
        return this.passwd;
    }

    /**
     * Set the value of the Passwd column.
     * @param passwd
     */
    public void setPasswd(java.lang.String passwd)
    {
        this.passwd = passwd;
    }

    /**
     * Return the value of the RoleID column.
     * @return Role
     */
    public java.lang.String getRoleid()
    {
        return this.roleid;
    }

    /**
     * Set the value of the RoleID column.
     * @param role
     */
    public void setRoleid(java.lang.String roleid)
    {
        this.roleid = roleid;
    }

    /**
     * Return the value of the StorageID column.
     * @return Unitinfo
     */
    public java.lang.String getStorageid()
    {
        return this.storageid;
    }

    /**
     * Set the value of the StorageID column.
     * @param unitinfo
     */
    public void setStorageid(java.lang.String storageid)
    {
        this.storageid = storageid;
    }
    
    /**
     * Return the value of the DutyID column.
     * @return Unitinfo
     */
    public java.lang.String getDutyid()
    {
        return this.dutyid;
    }

    /**
     * Set the value of the DutyID column.
     * @param unitinfo
     */
    public void setDutyid(java.lang.String dutyid)
    {
        this.dutyid = dutyid;
    }
    
    /**
     * Return the value of the OperRef column.
     * @return Unitinfo
     */
    public java.lang.String getOperref()
    {
        return this.operref;
    }

    /**
     * Set the value of the DutyID column.
     * @param unitinfo
     */
    public void setOperref(java.lang.String operref)
    {
        this.operref = operref;
    }

    /**
     * Return the value of the Phone column.
     * @return java.lang.String
     */
    public java.lang.String getPhone()
    {
        return this.phone;
    }

    /**
     * Set the value of the Phone column.
     * @param phone
     */
    public void setPhone(java.lang.String phone)
    {
        this.phone = phone;
    }

    /**
     * Return the value of the Fax column.
     * @return java.lang.String
     */
    public java.lang.String getFax()
    {
        return this.fax;
    }

    /**
     * Set the value of the Fax column.
     * @param fax
     */
    public void setFax(java.lang.String fax)
    {
        this.fax = fax;
    }

    /**
     * Return the value of the Email column.
     * @return java.lang.String
     */
    public java.lang.String getEmail()
    {
        return this.email;
    }

    /**
     * Set the value of the Email column.
     * @param email
     */
    public void setEmail(java.lang.String email)
    {
        this.email = email;
    }

    
    /**
     * Return the value of the EnabledFlag column.
     * @return java.lang.String
     */
    public java.lang.String getEnabledflag()
    {
        return this.enabledflag;
    }

    /**
     * Set the value of the EnabledFlag column.
     * @param enabledflag
     */
    public void setEnabledflag(java.lang.String enabledflag)
    {
        this.enabledflag = enabledflag;
    }

    /**
     * Return the value of the Rem1 column.
     * @return java.lang.String
     */
    public java.lang.String getRem1()
    {
        return this.rem1;
    }

    /**
     * Set the value of the Rem1 column.
     * @param rem1
     */
    public void setRem1(java.lang.String rem1)
    {
        this.rem1 = rem1;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Loginuser))
            return false;
        Loginuser that = (Loginuser) rhs;
        if (this.getUserid() == null || that.getUserid() == null)
            return false;
        return (this.getUserid().equals(that.getUserid()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int useridValue = this.getUserid() == null ? 0 : this.getUserid().hashCode();
            result = result * 37 + useridValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

	public String getGrcid() {
		return grcid;
	}

	public void setGrcid(String grcid) {
		this.grcid = grcid;
	}

	public java.lang.String getClass1id() {
		return class1id;
	}

	public void setClass1id(java.lang.String class1id) {
		this.class1id = class1id;
	}
}
