/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Oct 21 15:17:00 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.sysmanager;

import java.io.Serializable;

/**
 * A class that represents a row in the modulenode table. 
 * You can customize the behavior of this class by editing the class, {@link Modulenode()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractModulenode 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.String nodeid;

    /** The value of the module association. */
    private Module module;
    
    /** The value of the simple nodename property. */
    private java.lang.String moduleid;

    /** The value of the rolenodeSet one-to-many association. */
    private java.util.Set rolenodeSet;

    /** The value of the simple nodename property. */
    private java.lang.String nodename;

    /** The value of the simple nodeurl property. */
    private java.lang.String nodeurl;

    /** The value of the simple nodetarget property. */
    private java.lang.String nodetarget;
    
    /** The value of the simple level property. */
    private java.lang.Integer level;

    /** The value of the simple allowflag property. */
    private java.lang.String allowflag;

    /** The value of the simple nodeimage property. */
    private java.lang.String nodeimage;

    /** The value of the simple nodesort property. */
    private java.lang.Integer nodesort;

    /** The value of the simple nodedata property. */
    private java.lang.String nodedata;

    /** The value of the simple rem1 property. */
    private java.lang.String rem1;
    
    /** The value of the simple r1 property. */
    private java.lang.String r1;
    
    /** The value of the simple r2 property. */
    private java.lang.String r2;
    
    /** The value of the simple r3 property. */
    private java.lang.String r3;
    
    /** The value of the simple r4 property. */
    private java.lang.String r4;
    
    /** The value of the simple r5 property. */
    private java.lang.String r5;

    /**
     * Simple constructor of AbstractModulenode instances.
     */
    public AbstractModulenode()
    {
    }

    /**
     * Constructor of AbstractModulenode instances given a simple primary key.
     * @param nodeid
     */
    public AbstractModulenode(java.lang.String nodeid)
    {
        this.setNodeid(nodeid);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.String
     */
    public java.lang.String getNodeid()
    {
        return nodeid;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param nodeid
     */
    public void setNodeid(java.lang.String nodeid)
    {
        this.hashValue = 0;
        this.nodeid = nodeid;
    }

    /**
     * Return the value of the ModuleID column.
     * @return Module
     */
    public Module getModule()
    {
        return this.module;
    }

    /**
     * Set the value of the ModuleID column.
     * @param module
     */
    public void setModule(Module module)
    {
        this.module = module;
    }

    /**
     * Return the value of the NodeName column.
     * @return java.lang.String
     */
    public java.lang.String getNodename()
    {
        return this.nodename;
    }

    /**
     * Set the value of the NodeName column.
     * @param nodename
     */
    public void setNodename(java.lang.String nodename)
    {
        this.nodename = nodename;
    }

    /**
     * Return the value of the NodeURL column.
     * @return java.lang.String
     */
    public java.lang.String getNodeurl()
    {
        return this.nodeurl;
    }

    /**
     * Set the value of the NodeURL column.
     * @param nodeurl
     */
    public void setNodeurl(java.lang.String nodeurl)
    {
        this.nodeurl = nodeurl;
    }

    /**
     * Return the value of the NodeTarget column.
     * @return java.lang.String
     */
    public java.lang.String getNodetarget()
    {
        return this.nodetarget;
    }

    /**
     * Set the value of the NodeTarget column.
     * @param nodetarget
     */
    public void setNodetarget(java.lang.String nodetarget)
    {
        this.nodetarget = nodetarget;
    }

    /**
     * Return the value of the Level column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getLevel()
    {
        return this.level;
    }

    /**
     * Set the value of the Level column.
     * @param level
     */
    public void setLevel(java.lang.Integer level)
    {
        this.level = level;
    }

    /**
     * Return the value of the AllowFlag column.
     * @return java.lang.String
     */
    public java.lang.String getAllowflag()
    {
        return this.allowflag;
    }

    /**
     * Set the value of the AllowFlag column.
     * @param allowflag
     */
    public void setAllowflag(java.lang.String allowflag)
    {
        this.allowflag = allowflag;
    }

    /**
     * Return the value of the NodeImage column.
     * @return java.lang.String
     */
    public java.lang.String getNodeimage()
    {
        return this.nodeimage;
    }

    /**
     * Set the value of the NodeImage column.
     * @param nodeimage
     */
    public void setNodeimage(java.lang.String nodeimage)
    {
        this.nodeimage = nodeimage;
    }

    /**
     * Return the value of the NodeSort column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getNodesort()
    {
        return this.nodesort;
    }

    /**
     * Set the value of the NodeSort column.
     * @param nodesort
     */
    public void setNodesort(java.lang.Integer nodesort)
    {
        this.nodesort = nodesort;
    }

    /**
     * Return the value of the NodeData column.
     * @return java.lang.String
     */
    public java.lang.String getNodedata()
    {
        return this.nodedata;
    }

    /**
     * Set the value of the NodeData column.
     * @param nodedata
     */
    public void setNodedata(java.lang.String nodedata)
    {
        this.nodedata = nodedata;
    }

    /**
     * Return the value of the Rem1 column.
     * @return java.lang.String
     */
    public java.lang.String getRem1()
    {
        return this.rem1;
    }

    /**
     * Set the value of the Rem1 column.
     * @param rem1
     */
    public void setRem1(java.lang.String rem1)
    {
        this.rem1 = rem1;
    }

    /**
     * Return the value of the NodeID collection.
     * @return Rolenode
     */
    public java.util.Set getRolenodeSet()
    {
        return this.rolenodeSet;
    }

    /**
     * Set the value of the NodeID collection.
     * @param rolenodeSet
     */
    public void setRolenodeSet(java.util.Set rolenodeSet)
    {
        this.rolenodeSet = rolenodeSet;
    }
    
    /**
     * Return the value of the ModuleID column.
     * @return java.lang.String
     */
    public java.lang.String getModuleid()
    {
        return this.moduleid;
    }

    /**
     * Set the value of the ModuleID column.
     * @param ModuleID
     */
    public void setModuleid(java.lang.String moduleid)
    {
        this.moduleid = moduleid;
    }
    

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Modulenode))
            return false;
        Modulenode that = (Modulenode) rhs;
        if (this.getNodeid() == null || that.getNodeid() == null)
            return false;
        return (this.getNodeid().equals(that.getNodeid()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int nodeidValue = this.getNodeid() == null ? 0 : this.getNodeid().hashCode();
            result = result * 37 + nodeidValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

	public java.lang.String getR1() {
		return r1;
	}

	public void setR1(java.lang.String r1) {
		this.r1 = r1;
	}

	public java.lang.String getR2() {
		return r2;
	}

	public void setR2(java.lang.String r2) {
		this.r2 = r2;
	}

	public java.lang.String getR3() {
		return r3;
	}

	public void setR3(java.lang.String r3) {
		this.r3 = r3;
	}

	public java.lang.String getR4() {
		return r4;
	}

	public void setR4(java.lang.String r4) {
		this.r4 = r4;
	}

	public java.lang.String getR5() {
		return r5;
	}

	public void setR5(java.lang.String r5) {
		this.r5 = r5;
	}
}
