/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Nov 10 15:54:40 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.sysmanager;

import java.io.Serializable;

/**
 * A class that represents a row in the Company table. 
 * You can customize the behavior of this class by editing the class, {@link Company()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractCompany 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.String comid;

    /** The value of the storageidSet one-to-many association. */
    private java.util.Set storageidSet;

    /** The value of the simple comname property. */
    private java.lang.String comname;

    /** The value of the simple comfullname property. */
    private java.lang.String comfullname;

    /** The value of the simple comtype property. */
    private java.lang.String comtype;

    /** The value of the simple comtel property. */
    private java.lang.String comtel;

    /** The value of the simple linkman property. */
    private java.lang.String linkman;

    /** The value of the simple linkmantel property. */
    private java.lang.String linkmantel;

    /** The value of the simple fax property. */
    private java.lang.String fax;

    /** The value of the simple artperson property. */
    private java.lang.String artperson;

    /** The value of the simple bank property. */
    private java.lang.String bank;

    /** The value of the simple account property. */
    private java.lang.String account;

    /** The value of the simple address property. */
    private java.lang.String address;

    /** The value of the simple enabledflag property. */
    private java.lang.String enabledflag;

    /** The value of the simple rem property. */
    private java.lang.String rem;

    /**
     * Simple constructor of AbstractCompany instances.
     */
    public AbstractCompany()
    {
    }

    /**
     * Constructor of AbstractCompany instances given a simple primary key.
     * @param comid
     */
    public AbstractCompany(java.lang.String comid)
    {
        this.setComid(comid);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.String
     */
    public java.lang.String getComid()
    {
        return comid;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param comid
     */
    public void setComid(java.lang.String comid)
    {
        this.hashValue = 0;
        this.comid = comid;
    }

    /**
     * Return the value of the ComName column.
     * @return java.lang.String
     */
    public java.lang.String getComname()
    {
        return this.comname;
    }

    /**
     * Set the value of the ComName column.
     * @param comname
     */
    public void setComname(java.lang.String comname)
    {
        this.comname = comname;
    }

    /**
     * Return the value of the ComFullName column.
     * @return java.lang.String
     */
    public java.lang.String getComfullname()
    {
        return this.comfullname;
    }

    /**
     * Set the value of the ComFullName column.
     * @param comfullname
     */
    public void setComfullname(java.lang.String comfullname)
    {
        this.comfullname = comfullname;
    }

    /**
     * Return the value of the ComType column.
     * @return java.lang.String
     */
    public java.lang.String getComtype()
    {
        return this.comtype;
    }

    /**
     * Set the value of the ComType column.
     * @param comtype
     */
    public void setComtype(java.lang.String comtype)
    {
        this.comtype = comtype;
    }

    /**
     * Return the value of the ComTel column.
     * @return java.lang.String
     */
    public java.lang.String getComtel()
    {
        return this.comtel;
    }

    /**
     * Set the value of the ComTel column.
     * @param comtel
     */
    public void setComtel(java.lang.String comtel)
    {
        this.comtel = comtel;
    }

    /**
     * Return the value of the LinkMan column.
     * @return java.lang.String
     */
    public java.lang.String getLinkman()
    {
        return this.linkman;
    }

    /**
     * Set the value of the LinkMan column.
     * @param linkman
     */
    public void setLinkman(java.lang.String linkman)
    {
        this.linkman = linkman;
    }

    /**
     * Return the value of the LinkManTel column.
     * @return java.lang.String
     */
    public java.lang.String getLinkmantel()
    {
        return this.linkmantel;
    }

    /**
     * Set the value of the LinkManTel column.
     * @param linkmantel
     */
    public void setLinkmantel(java.lang.String linkmantel)
    {
        this.linkmantel = linkmantel;
    }

    /**
     * Return the value of the Fax column.
     * @return java.lang.String
     */
    public java.lang.String getFax()
    {
        return this.fax;
    }

    /**
     * Set the value of the Fax column.
     * @param fax
     */
    public void setFax(java.lang.String fax)
    {
        this.fax = fax;
    }

    /**
     * Return the value of the ArtPerson column.
     * @return java.lang.String
     */
    public java.lang.String getArtperson()
    {
        return this.artperson;
    }

    /**
     * Set the value of the ArtPerson column.
     * @param artperson
     */
    public void setArtperson(java.lang.String artperson)
    {
        this.artperson = artperson;
    }

    /**
     * Return the value of the Bank column.
     * @return java.lang.String
     */
    public java.lang.String getBank()
    {
        return this.bank;
    }

    /**
     * Set the value of the Bank column.
     * @param bank
     */
    public void setBank(java.lang.String bank)
    {
        this.bank = bank;
    }

    /**
     * Return the value of the Account column.
     * @return java.lang.String
     */
    public java.lang.String getAccount()
    {
        return this.account;
    }

    /**
     * Set the value of the Account column.
     * @param account
     */
    public void setAccount(java.lang.String account)
    {
        this.account = account;
    }

    /**
     * Return the value of the Address column.
     * @return java.lang.String
     */
    public java.lang.String getAddress()
    {
        return this.address;
    }

    /**
     * Set the value of the Address column.
     * @param address
     */
    public void setAddress(java.lang.String address)
    {
        this.address = address;
    }

    /**
     * Return the value of the EnabledFlag column.
     * @return java.lang.String
     */
    public java.lang.String getEnabledflag()
    {
        return this.enabledflag;
    }

    /**
     * Set the value of the EnabledFlag column.
     * @param enabledflag
     */
    public void setEnabledflag(java.lang.String enabledflag)
    {
        this.enabledflag = enabledflag;
    }

    /**
     * Return the value of the Rem column.
     * @return java.lang.String
     */
    public java.lang.String getRem()
    {
        return this.rem;
    }

    /**
     * Set the value of the Rem column.
     * @param rem
     */
    public void setRem(java.lang.String rem)
    {
        this.rem = rem;
    }

    /**
     * Return the value of the ComID collection.
     * @return Storageid
     */
    public java.util.Set getStorageidSet()
    {
        return this.storageidSet;
    }

    /**
     * Set the value of the ComID collection.
     * @param storageidSet
     */
    public void setStorageidSet(java.util.Set storageidSet)
    {
        this.storageidSet = storageidSet;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Company))
            return false;
        Company that = (Company) rhs;
        if (this.getComid() == null || that.getComid() == null)
            return false;
        return (this.getComid().equals(that.getComid()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int comidValue = this.getComid() == null ? 0 : this.getComid().hashCode();
            result = result * 37 + comidValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
