/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Oct 21 13:29:41 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.sysmanager;

import java.io.Serializable;

/**
 * A class that represents a row in the module table. 
 * You can customize the behavior of this class by editing the class, {@link Module()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractModule 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.String moduleid;

    /** The value of the modulenodeSet one-to-many association. */
    private java.util.Set modulenodeSet;

    /** The value of the roleSet one-to-many association. */
    private java.util.Set roleSet;

    /** The value of the simple modulename property. */
    private java.lang.String modulename;

    /** The value of the simple enableflag property. */
    private java.lang.String enabledflag;

    /** The value of the simple rem1 property. */
    private java.lang.String rem1;

    /**
     * Simple constructor of AbstractModule instances.
     */
    public AbstractModule()
    {
    }

    /**
     * Constructor of AbstractModule instances given a simple primary key.
     * @param moduleid
     */
    public AbstractModule(java.lang.String moduleid)
    {
        this.setModuleid(moduleid);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.String
     */
    public java.lang.String getModuleid()
    {
        return moduleid;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param moduleid
     */
    public void setModuleid(java.lang.String moduleid)
    {
        this.hashValue = 0;
        this.moduleid = moduleid;
    }

    /**
     * Return the value of the ModuleName column.
     * @return java.lang.String
     */
    public java.lang.String getModulename()
    {
        return this.modulename;
    }

    /**
     * Set the value of the ModuleName column.
     * @param modulename
     */
    public void setModulename(java.lang.String modulename)
    {
        this.modulename = modulename;
    }

    /**
     * Return the value of the EnableFlag column.
     * @return java.lang.String
     */
    public java.lang.String getEnabledflag()
    {
        return this.enabledflag;
    }

    /**
     * Set the value of the EnableFlag column.
     * @param enableflag
     */
    public void setEnabledflag(java.lang.String enabledflag)
    {
        this.enabledflag = enabledflag;
    }

    /**
     * Return the value of the Rem1 column.
     * @return java.lang.String
     */
    public java.lang.String getRem1()
    {
        return this.rem1;
    }

    /**
     * Set the value of the Rem1 column.
     * @param rem1
     */
    public void setRem1(java.lang.String rem1)
    {
        this.rem1 = rem1;
    }

    /**
     * Return the value of the ModuleID collection.
     * @return Modulenode
     */
    public java.util.Set getModulenodeSet()
    {
        return this.modulenodeSet;
    }

    /**
     * Set the value of the ModuleID collection.
     * @param modulenodeSet
     */
    public void setModulenodeSet(java.util.Set modulenodeSet)
    {
        this.modulenodeSet = modulenodeSet;
    }

    /**
     * Return the value of the ModuleId collection.
     * @return Role
     */
    public java.util.Set getRoleSet()
    {
        return this.roleSet;
    }

    /**
     * Set the value of the ModuleId collection.
     * @param roleSet
     */
    public void setRoleSet(java.util.Set roleSet)
    {
        this.roleSet = roleSet;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Module))
            return false;
        Module that = (Module) rhs;
        if (this.getModuleid() == null || that.getModuleid() == null)
            return false;
        return (this.getModuleid().equals(that.getModuleid()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int moduleidValue = this.getModuleid() == null ? 0 : this.getModuleid().hashCode();
            result = result * 37 + moduleidValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
