/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Oct 21 13:28:59 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.sysmanager;

import java.io.Serializable;

/**
 * A class representing a composite primary key id for the GetNum
 * table.  This object should only be instantiated for use with instances 
 * of the Getnum class.
 */
public class GetnumKey
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private volatile int hashValue = 0;

    /** The value of the DeptFlag component of this composite id. */
    private java.lang.String deptflag;

    /** The value of the Year1 component of this composite id. */
    private java.lang.String year1;

    /**
     * Simple constructor of GetnumKey instances.
     */
    public GetnumKey()
    {
    }

    /**
     * Returns the value of the deptflag property.
     * @return java.lang.Integer
     */
    public java.lang.String getDeptflag()
    {
    	return deptflag;
    }

    /**
     * Sets the value of the deptflag property.
     * @param deptflag
     */
    public void setDeptflag(java.lang.String deptflag)
    {
        hashValue = 0;
        this.deptflag = deptflag;
    }

    /**
     * Returns the value of the year1 property.
     * @return java.lang.String
     */
    public java.lang.String getYear1()
    {
        return year1;
    }

    /**
     * Sets the value of the year1 property.
     * @param year1
     */
    public void setYear1(java.lang.String year1)
    {
        hashValue = 0;
        this.year1 = year1;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the id components.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof GetnumKey))
            return false;
        GetnumKey that = (GetnumKey) rhs;
        if (this.getDeptflag() == null || that.getDeptflag() == null)
        {
            return false;
        }
        if (! this.getDeptflag().equals(that.getDeptflag()))
        {
            return false;
        }
        if (this.getYear1() == null || that.getYear1() == null)
        {
            return false;
        }
        if (! this.getYear1().equals(that.getYear1()))
        {
            return false;
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int deptflagValue = this.getDeptflag() == null ? 0 : this.getDeptflag().hashCode();
            result = result * 37 + deptflagValue;
            int year1Value = this.getYear1() == null ? 0 : this.getYear1().hashCode();
            result = result * 37 + year1Value;
            this.hashValue = result;
        }
        return this.hashValue;
    }

	
}
