/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Mar 08 11:11:31 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.sysmanager;

import java.io.Serializable;

/**
 * A class representing a composite primary key id for the OperationRef
 * table.  This object should only be instantiated for use with instances 
 * of the Operationref class.
 */
public class OperationrefKey
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private volatile int hashValue = 0;

    /** The value of the OperationID component of this composite id. */
    private java.lang.String operationid;

    /** The value of the UserID component of this composite id. */
    private Loginuser loginuser;
    
    private java.lang.String userid;

    /**
     * Simple constructor of OperationrefKey instances.
     */
    public OperationrefKey()
    {
    }

    /**
     * Returns the value of the operationid property.
     * @return java.lang.String
     */
    public java.lang.String getOperationid()
    {
        return operationid;
    }
    
  

    /**
     * Sets the value of the operationid property.
     * @param operationid
     */
    public void setOperationid(java.lang.String operationid)
    {
        hashValue = 0;
        this.operationid = operationid;
    }

    /**
     * Returns the value of the loginuser property.
     * @return Loginuser
     */
    public Loginuser getLoginuser()
    {
        return loginuser;
    }

    /**
     * Sets the value of the loginuser property.
     * @param loginuser
     */
    public void setLoginuser(Loginuser loginuser)
    {
        hashValue = 0;
        this.loginuser = loginuser;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the id components.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof OperationrefKey))
            return false;
        OperationrefKey that = (OperationrefKey) rhs;
        if (this.getOperationid() == null || that.getOperationid() == null)
        {
            return false;
        }
        if (! this.getOperationid().equals(that.getOperationid()))
        {
            return false;
        }
        if (this.getUserid() == null || that.getUserid() == null)
        {
            return false;
        }
        if (! this.getUserid().equals(that.getUserid()))
        {
            return false;
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int operationidValue = this.getOperationid() == null ? 0 : this.getOperationid().hashCode();
            result = result * 37 + operationidValue;
            int loginuserValue = this.getUserid() == null ? 0 : this.getUserid().hashCode();
            result = result * 37 + loginuserValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

	public java.lang.String getUserid() {
		return userid;
	}

	public void setUserid(java.lang.String userid) {
		this.userid = userid;
	}
}
