/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Jun 14 14:47:56 CST 2007 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.sysmanager;

import java.io.Serializable;

/**
 * A class representing a composite primary key id for the UserAreaRef
 * table.  This object should only be instantiated for use with instances 
 * of the Userarearef class.
 */
public class UserarearefKey
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private volatile int hashValue = 0;

    /** The value of the AreaID component of this composite id. */
    private String areaid;

    /** The value of the UserID component of this composite id. */
    private String userid;

    /**
     * Simple constructor of UserarearefKey instances.
     */
    public UserarearefKey()
    {
    }


    /**
     * Implementation of the equals comparison on the basis of equality of the id components.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof UserarearefKey))
            return false;
        UserarearefKey that = (UserarearefKey) rhs;
        if (this.getAreaid() == null || that.getAreaid() == null)
        {
            return false;
        }
        if (! this.getAreaid().equals(that.getAreaid()))
        {
            return false;
        }
        if (this.getUserid() == null || that.getUserid() == null)
        {
            return false;
        }
        if (! this.getUserid().equals(that.getUserid()))
        {
            return false;
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int areaValue = this.getAreaid() == null ? 0 : this.getAreaid().hashCode();
            result = result * 37 + areaValue;
            int loginuserValue = this.getUserid() == null ? 0 : this.getAreaid().hashCode();
            result = result * 37 + loginuserValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }


	public String getAreaid() {
		return areaid;
	}


	public void setAreaid(String areaid) {
		this.areaid = areaid;
	}


	public String getUserid() {
		return userid;
	}


	public void setUserid(String userid) {
		this.userid = userid;
	}
}
