/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Jan 22 17:53:40 CST 2008 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.sysmanager;

import java.io.Serializable;

/**
 * A class representing a composite primary key id for the WsRoleConfig
 * table.  This object should only be instantiated for use with instances 
 * of the Wsroleconfig class.
 */
public class WsroleconfigKey
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private volatile int hashValue = 0;

    /** The value of the RoleID component of this composite id. */
    private String roleid;

    /** The value of the WsId component of this composite id. */
    private String  wsid;

    /**
     * Simple constructor of WsroleconfigKey instances.
     */
    public WsroleconfigKey()
    {
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the id components.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof WsroleconfigKey))
            return false;
        WsroleconfigKey that = (WsroleconfigKey) rhs;
        if (this.getRoleid() == null || that.getRoleid() == null)
        {
            return false;
        }
        if (! this.getRoleid().equals(that.getRoleid()))
        {
            return false;
        }
        if (this.getWsid() == null || that.getWsid() == null)
        {
            return false;
        }
        if (! this.getWsid().equals(that.getWsid()))
        {
            return false;
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int roleValue = this.getRoleid() == null ? 0 : this.getRoleid().hashCode();
            result = result * 37 + roleValue;
            int workspacebasepropertyValue = this.getWsid() == null ? 0 : this.getWsid().hashCode();
            result = result * 37 + workspacebasepropertyValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

	public String getRoleid() {
		return roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

	public String getWsid() {
		return wsid;
	}

	public void setWsid(String wsid) {
		this.wsid = wsid;
	}
}
