/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Nov 11 16:40:23 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.viewmanager;

import java.io.Serializable;

/**
 * A class that represents a row in the ViewDuty table. 
 * You can customize the behavior of this class by editing the class, {@link Viewduty()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractViewduty 
    implements Serializable
{

    /** The value of the simple dutyid property. */
    private java.lang.String dutyid;

    /** The value of the simple dutyname property. */
    private java.lang.String dutyname;

    /**
     * Simple constructor of AbstractViewduty instances.
     */
    public AbstractViewduty()
    {
    }

    /**
     * Return the value of the DutyID column.
     * @return java.lang.String
     */
    public java.lang.String getDutyid()
    {
        return this.dutyid;
    }

    /**
     * Set the value of the DutyID column.
     * @param dutyid
     */
    public void setDutyid(java.lang.String dutyid)
    {
        this.dutyid = dutyid;
    }

    /**
     * Return the value of the DutyName column.
     * @return java.lang.String
     */
    public java.lang.String getDutyname()
    {
        return this.dutyname;
    }

    /**
     * Set the value of the DutyName column.
     * @param dutyname
     */
    public void setDutyname(java.lang.String dutyname)
    {
        this.dutyname = dutyname;
    }
}
