/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Nov 29 15:12:51 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.viewmanager;

import java.io.Serializable;

/**
 * A class that represents a row in the ViewUserAllowFlagY table. 
 * You can customize the behavior of this class by editing the class, {@link Viewuserallowflagy()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractViewuserallowflagy 
    implements Serializable
{

    /** The value of the simple userid property. */
    private java.lang.String userid;

    /** The value of the simple username property. */
    private java.lang.String username;

    /** The value of the simple storageid property. */
    private java.lang.String storageid;

    /** The value of the simple userref property. */
    private java.lang.String userref;

    /** The value of the simple roleid property. */
    private java.lang.String roleid;

    /** The value of the simple rolename property. */
    private java.lang.String rolename;

    /**
     * Simple constructor of AbstractViewuserallowflagy instances.
     */
    public AbstractViewuserallowflagy()
    {
    }

    /**
     * Return the value of the UserID column.
     * @return java.lang.String
     */
    public java.lang.String getUserid()
    {
        return this.userid;
    }

    /**
     * Set the value of the UserID column.
     * @param userid
     */
    public void setUserid(java.lang.String userid)
    {
        this.userid = userid;
    }

    /**
     * Return the value of the UserName column.
     * @return java.lang.String
     */
    public java.lang.String getUsername()
    {
        return this.username;
    }

    /**
     * Set the value of the UserName column.
     * @param username
     */
    public void setUsername(java.lang.String username)
    {
        this.username = username;
    }

    /**
     * Return the value of the StorageID column.
     * @return java.lang.String
     */
    public java.lang.String getStorageid()
    {
        return this.storageid;
    }

    /**
     * Set the value of the StorageID column.
     * @param storageid
     */
    public void setStorageid(java.lang.String storageid)
    {
        this.storageid = storageid;
    }

    /**
     * Return the value of the UserRef column.
     * @return java.lang.String
     */
    public java.lang.String getUserref()
    {
        return this.userref;
    }

    /**
     * Set the value of the UserRef column.
     * @param userref
     */
    public void setUserref(java.lang.String userref)
    {
        this.userref = userref;
    }

    /**
     * Return the value of the RoleID column.
     * @return java.lang.String
     */
    public java.lang.String getRoleid()
    {
        return this.roleid;
    }

    /**
     * Set the value of the RoleID column.
     * @param roleid
     */
    public void setRoleid(java.lang.String roleid)
    {
        this.roleid = roleid;
    }

    /**
     * Return the value of the RoleName column.
     * @return java.lang.String
     */
    public java.lang.String getRolename()
    {
        return this.rolename;
    }

    /**
     * Set the value of the RoleName column.
     * @param rolename
     */
    public void setRolename(java.lang.String rolename)
    {
        this.rolename = rolename;
    }
}
