/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Nov 10 19:00:13 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.viewmanager;

import java.io.Serializable;

/**
 * A class that represents a row in the ViewCompanyType table. 
 * You can customize the behavior of this class by editing the class, {@link Viewcompanytype()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractViewcompanytype 
    implements Serializable
{

    /** The value of the simple comtypeid property. */
    private java.lang.String comtypeid;

    /** The value of the simple comtypename property. */
    private java.lang.String comtypename;

    /**
     * Simple constructor of AbstractViewcompanytype instances.
     */
    public AbstractViewcompanytype()
    {
    }

    /**
     * Return the value of the ComTypeID column.
     * @return java.lang.String
     */
    public java.lang.String getComtypeid()
    {
        return this.comtypeid;
    }

    /**
     * Set the value of the ComTypeID column.
     * @param comtypeid
     */
    public void setComtypeid(java.lang.String comtypeid)
    {
        this.comtypeid = comtypeid;
    }

    /**
     * Return the value of the ComTypeName column.
     * @return java.lang.String
     */
    public java.lang.String getComtypename()
    {
        return this.comtypename;
    }

    /**
     * Set the value of the ComTypeName column.
     * @param comtypename
     */
    public void setComtypename(java.lang.String comtypename)
    {
        this.comtypename = comtypename;
    }
}
