/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Nov 16 14:25:12 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.viewmanager;

import java.io.Serializable;

/**
 * A class that represents a row in the ViewAllowFlag table. 
 * You can customize the behavior of this class by editing the class, {@link Viewallowflag()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractViewallowflag 
    implements Serializable
{

    /** The value of the simple flagid property. */
    private java.lang.String flagid;

    /** The value of the simple flagname property. */
    private java.lang.String flagname;

    /**
     * Simple constructor of AbstractViewallowflag instances.
     */
    public AbstractViewallowflag()
    {
    }

    /**
     * Return the value of the FlagID column.
     * @return java.lang.String
     */
    public java.lang.String getFlagid()
    {
        return this.flagid;
    }

    /**
     * Set the value of the FlagID column.
     * @param flagid
     */
    public void setFlagid(java.lang.String flagid)
    {
        this.flagid = flagid;
    }

    /**
     * Return the value of the FlagName column.
     * @return java.lang.String
     */
    public java.lang.String getFlagname()
    {
        return this.flagname;
    }

    /**
     * Set the value of the FlagName column.
     * @param flagname
     */
    public void setFlagname(java.lang.String flagname)
    {
        this.flagname = flagname;
    }
}
