/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Sun Jul 10 19:12:47 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.viewmanager;

import java.io.Serializable;

/**
 * 对应用户ViewLoginUserInfo视图的抽象类
 * A class that represents a row in the ViewLoginUserInfo table. 
 * You can customize the behavior of this class by editing the class, {@link Viewloginuserinfo()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractViewLoginUserInfo 
    implements Serializable
{

    /** The value of the simple userid property. */
    private java.lang.String userID;

    /** The value of the simple username property. */
    private java.lang.String userName;

    /** The value of the simple passwd property. */
    private java.lang.String passwd;

    /** The value of the simple roleid property. */
    private java.lang.String roleID;

    /** The value of the simple rolename property. */
    private java.lang.String roleName;

    /** The value of the simple moduleid property. */
    private java.lang.String moduleID;

    /** The value of the simple modulename property. */
    private java.lang.String moduleName;

    /** The value of the simple enabledflag property. */
    private java.lang.String enabledFlag;
    
    private java.lang.String storageId;
    private java.lang.String storageName;
    /** The value of the simple rem1 property. */
    private java.lang.String rem1;
    private java.lang.String class1;
    private java.lang.String comID;
    private java.lang.String comName;
    private java.lang.String phoneimei;
    private java.lang.String phone;
    
    
    public java.lang.String getPhone() {
		return phone;
	}

	public void setPhone(java.lang.String phone) {
		this.phone = phone;
	}

	public java.lang.String getPhoneimei() {
		return phoneimei;
	}

	public void setPhoneimei(java.lang.String phoneimei) {
		this.phoneimei = phoneimei;
	}

	public java.lang.String getComName() {
		return comName;
	}

	public void setComName(java.lang.String comName) {
		this.comName = comName;
	}

	public java.lang.String getComID() {
		return comID;
	}

	public void setComID(java.lang.String comID) {
		this.comID = comID;
	}

	public java.lang.String getStorageName() {
		return storageName;
	}

	public void setStorageName(java.lang.String storageName) {
		this.storageName = storageName;
	}

	public java.lang.String getClass1() {
		return class1;
	}

	public void setClass1(java.lang.String class1) {
		this.class1 = class1;
	}

	
	
	public void setStorageId(java.lang.String storageId) {
		this.storageId = storageId;
	}

	/**
     * Simple constructor of AbstractViewloginuserinfo instances.
     */
    public AbstractViewLoginUserInfo()
    {
    }

    /**
     * Return the value of the UserID column.
     * @return java.lang.String
     */
    public java.lang.String getUserID()
    {
        return this.userID;
    }

    /**
     * Set the value of the UserID column.
     * @param userid
     */
    public void setUserID(java.lang.String userid)
    {
        this.userID = userid;
    }

    /**
     * Return the value of the UserName column.
     * @return java.lang.String
     */
    public java.lang.String getUserName()
    {
        return this.userName;
    }

    /**
     * Set the value of the UserName column.
     * @param username
     */
    public void setUserName(java.lang.String username)
    {
        this.userName = username;
    }

    /**
     * Return the value of the Passwd column.
     * @return java.lang.String
     */
    public java.lang.String getPasswd()
    {
        return this.passwd;
    }

    /**
     * Set the value of the Passwd column.
     * @param passwd
     */
    public void setPasswd(java.lang.String passwd)
    {
        this.passwd = passwd;
    }
    
    /**
     * Return the value of the RoleID column.
     * @return java.lang.String
     */
    public java.lang.String getRoleID()
    {
        return this.roleID;
    }

    /**
     * Set the value of the RoleID column.
     * @param roleid
     */
    public void setRoleID(java.lang.String roleid)
    {
        this.roleID = roleid;
    }

    /**
     * Return the value of the RoleName column.
     * @return java.lang.String
     */
    public java.lang.String getRoleName()
    {
        return this.roleName;
    }

    /**
     * Set the value of the RoleName column.
     * @param rolename
     */
    public void setRoleName(java.lang.String rolename)
    {
        this.roleName = rolename;
    }

    /**
     * Return the value of the ModuleID column.
     * @return java.lang.String
     */
    public java.lang.String getModuleID()
    {
        return this.moduleID;
    }

    /**
     * Set the value of the ModuleID column.
     * @param moduleid
     */
    public void setModuleID(java.lang.String moduleid)
    {
        this.moduleID = moduleid;
    }

    /**
     * Return the value of the ModuleName column.
     * @return java.lang.String
     */
    public java.lang.String getModuleName()
    {
        return this.moduleName;
    }

    /**
     * Set the value of the ModuleName column.
     * @param modulename
     */
    public void setModuleName(java.lang.String modulename)
    {
        this.moduleName = modulename;
    }

    /**
     * Return the value of the EnabledFlag column.
     * @return java.lang.String
     */
    public java.lang.String getEnabledFlag()
    {
        return this.enabledFlag;
    }

    /**
     * Set the value of the EnabledFlag column.
     * @param enabledflag
     */
    public void setEnabledFlag(java.lang.String enabledflag)
    {
        this.enabledFlag = enabledflag;
    }

    /**
     * Return the value of the Rem1 column.
     * @return java.lang.String
     */
    public java.lang.String getRem1()
    {
        return this.rem1;
    }

    /**
     * Set the value of the Rem1 column.
     * @param rem1
     */
    public void setRem1(java.lang.String rem1)
    {
        this.rem1 = rem1;
    }

	public java.lang.String getStorageId() {
		return storageId;
	}
    
    
}
