/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Dec 13 14:18:39 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.viewmanager;

import java.io.Serializable;

/**
 * A class that represents a row in the ViewStorageType table. 
 * You can customize the behavior of this class by editing the class, {@link Viewstoragetype()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractViewstoragetype 
    implements Serializable
{

    /** The value of the simple typeid property. */
    private java.lang.String typeid;

    /** The value of the simple typename property. */
    private java.lang.String typename;

    /**
     * Simple constructor of AbstractViewstoragetype instances.
     */
    public AbstractViewstoragetype()
    {
    }

    /**
     * Return the value of the TypeID column.
     * @return java.lang.String
     */
    public java.lang.String getTypeid()
    {
        return this.typeid;
    }

    /**
     * Set the value of the TypeID column.
     * @param typeid
     */
    public void setTypeid(java.lang.String typeid)
    {
        this.typeid = typeid;
    }

    /**
     * Return the value of the TypeName column.
     * @return java.lang.String
     */
    public java.lang.String getTypename()
    {
        return this.typename;
    }

    /**
     * Set the value of the TypeName column.
     * @param typename
     */
    public void setTypename(java.lang.String typename)
    {
        this.typename = typename;
    }
}
