/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Oct 21 13:27:12 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.viewmanager;

import java.io.Serializable;

/**
 * A class that represents a row in the ViewUserRoleNode table. 
 * You can customize the behavior of this class by editing the class, {@link Viewuserrolenode()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractViewuserrolenode 
    implements Serializable
{

    /** The value of the simple userid property. */
    private java.lang.String userid;

    /** The value of the simple nodeid property. */
    private java.lang.String nodeid;

    /** The value of the simple moduleid property. */
    private java.lang.String moduleid;

    /** The value of the simple nodename property. */
    private java.lang.String nodename;

    /** The value of the simple nodeurl property. */
    private java.lang.String nodeurl;

    /** The value of the simple nodetarget property. */
    private java.lang.String nodetarget;

    /** The value of the simple level property. */
    private java.lang.Integer level;

    /** The value of the simple allowflag property. */
    private java.lang.String allowflag;

    /** The value of the simple nodeimage property. */
    private java.lang.String nodeimage;

    /** The value of the simple nodesort property. */
    private java.lang.Integer nodesort;

    /** The value of the simple nodedata property. */
    private java.lang.String nodedata;

    /** The value of the simple rem1 property. */
    private java.lang.String rem1;

    /**
     * Simple constructor of AbstractViewuserrolenode instances.
     */
    public AbstractViewuserrolenode()
    {
    }

    /**
     * Return the value of the UserID column.
     * @return java.lang.String
     */
    public java.lang.String getUserid()
    {
        return this.userid;
    }

    /**
     * Set the value of the UserID column.
     * @param userid
     */
    public void setUserid(java.lang.String userid)
    {
        this.userid = userid;
    }

    /**
     * Return the value of the NodeID column.
     * @return java.lang.String
     */
    public java.lang.String getNodeid()
    {
        return this.nodeid;
    }

    /**
     * Set the value of the NodeID column.
     * @param nodeid
     */
    public void setNodeid(java.lang.String nodeid)
    {
        this.nodeid = nodeid;
    }

    /**
     * Return the value of the ModuleID column.
     * @return java.lang.String
     */
    public java.lang.String getModuleid()
    {
        return this.moduleid;
    }

    /**
     * Set the value of the ModuleID column.
     * @param moduleid
     */
    public void setModuleid(java.lang.String moduleid)
    {
        this.moduleid = moduleid;
    }

    /**
     * Return the value of the NodeName column.
     * @return java.lang.String
     */
    public java.lang.String getNodename()
    {
        return this.nodename;
    }

    /**
     * Set the value of the NodeName column.
     * @param nodename
     */
    public void setNodename(java.lang.String nodename)
    {
        this.nodename = nodename;
    }

    /**
     * Return the value of the NodeURL column.
     * @return java.lang.String
     */
    public java.lang.String getNodeurl()
    {
        return this.nodeurl;
    }

    /**
     * Set the value of the NodeURL column.
     * @param nodeurl
     */
    public void setNodeurl(java.lang.String nodeurl)
    {
        this.nodeurl = nodeurl;
    }

    /**
     * Return the value of the NodeTarget column.
     * @return java.lang.String
     */
    public java.lang.String getNodetarget()
    {
        return this.nodetarget;
    }

    /**
     * Set the value of the NodeTarget column.
     * @param nodetarget
     */
    public void setNodetarget(java.lang.String nodetarget)
    {
        this.nodetarget = nodetarget;
    }

    /**
     * Return the value of the Level column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getLevel()
    {
        return this.level;
    }

    /**
     * Set the value of the Level column.
     * @param level
     */
    public void setLevel(java.lang.Integer level)
    {
        this.level = level;
    }

    /**
     * Return the value of the AllowFlag column.
     * @return java.lang.String
     */
    public java.lang.String getAllowflag()
    {
        return this.allowflag;
    }

    /**
     * Set the value of the AllowFlag column.
     * @param allowflag
     */
    public void setAllowflag(java.lang.String allowflag)
    {
        this.allowflag = allowflag;
    }

    /**
     * Return the value of the NodeImage column.
     * @return java.lang.String
     */
    public java.lang.String getNodeimage()
    {
        return this.nodeimage;
    }

    /**
     * Set the value of the NodeImage column.
     * @param nodeimage
     */
    public void setNodeimage(java.lang.String nodeimage)
    {
        this.nodeimage = nodeimage;
    }

    /**
     * Return the value of the NodeSort column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getNodesort()
    {
        return this.nodesort;
    }

    /**
     * Set the value of the NodeSort column.
     * @param nodesort
     */
    public void setNodesort(java.lang.Integer nodesort)
    {
        this.nodesort = nodesort;
    }

    /**
     * Return the value of the NodeData column.
     * @return java.lang.String
     */
    public java.lang.String getNodedata()
    {
        return this.nodedata;
    }

    /**
     * Set the value of the NodeData column.
     * @param nodedata
     */
    public void setNodedata(java.lang.String nodedata)
    {
        this.nodedata = nodedata;
    }

    /**
     * Return the value of the rem1 column.
     * @return java.lang.String
     */
    public java.lang.String getRem1()
    {
        return this.rem1;
    }

    /**
     * Set the value of the rem1 column.
     * @param rem1
     */
    public void setRem1(java.lang.String rem1)
    {
        this.rem1 = rem1;
    }
}
