/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Dec 13 19:48:32 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.viewmanager;

import java.io.Serializable;

/**
 * A class that represents a row in the ViewMugStorage table. 
 * You can customize the behavior of this class by editing the class, {@link Viewmugstorage()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractViewmugstorage 
    implements Serializable
{

    /** The value of the simple storageid property. */
    private java.lang.String storageid;

    /** The value of the simple storagename property. */
    private java.lang.String storagename;

    /**
     * Simple constructor of AbstractViewmugstorage instances.
     */
    public AbstractViewmugstorage()
    {
    }

    /**
     * Return the value of the StorageID column.
     * @return java.lang.String
     */
    public java.lang.String getStorageid()
    {
        return this.storageid;
    }

    /**
     * Set the value of the StorageID column.
     * @param storageid
     */
    public void setStorageid(java.lang.String storageid)
    {
        this.storageid = storageid;
    }

    /**
     * Return the value of the StorageName column.
     * @return java.lang.String
     */
    public java.lang.String getStoragename()
    {
        return this.storagename;
    }

    /**
     * Set the value of the StorageName column.
     * @param storagename
     */
    public void setStoragename(java.lang.String storagename)
    {
        this.storagename = storagename;
    }
}
