<%@ taglib uri="/WEB-INF/tld/struts-bean.tld" prefix="bean" %>
<%@ taglib uri="/WEB-INF/tld/struts-html.tld" prefix="html" %>
<%@ taglib uri="/WEB-INF/tld/struts-logic.tld" prefix="logic" %>
<%@ taglib uri="/WEB-INF/tld/html-table.tld" prefix="table" %>
<%@ taglib uri="/WEB-INF/tld/struts-tiles.tld" prefix="tiles" %>

<tiles:insert page="/jsp/template.jsp" flush="true">

  <tiles:put name="title" value="User-controlled columns"/>

  <tiles:put name="body" direct="true">

    <html:link page="/AdjustTableEdit.do" name="adjustTableParameters">
      <html:img page="/images/adjust.jpg" border="0"/></html:link>
    Click on the icon to the left to adjust visibility and sort order of the columns

    <table:table id="guiCustomersAdjustable" name="customerListW">
      <logic:iterate id="element" name="customerListW">

        <bean:define id="c_id" name="element" property="id"/>
        <bean:define id="c_name" name="element" property="name"/>
        <bean:define id="c_conname" name="element" property="contactName"/>
        <bean:define id="c_contitle" name="element" property="contactTitle"/>
        <table:define id="c_phone">
          <bean:write name="element" property="phone"/>
        </table:define>
        <bean:define id="c_city" name="element" property="city"/>
        <bean:define id="c_country" name="element" property="country"/>

        <table:tr/>

      </logic:iterate>
    </table:table>
  
  </tiles:put>
  
  <tiles:put name="xmlConfig" direct="true">guiCustomersAdjustable</tiles:put>
  
  <tiles:put name="jspConfig" direct="true">
<PRE><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">&lt;</SPAN><SPAN CLASS="syntax10">html</SPAN><SPAN CLASS="syntax10">:</SPAN><SPAN CLASS="syntax9">link</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">page</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">/</SPAN><SPAN CLASS="syntax3">AdjustTableEdit</SPAN><SPAN CLASS="syntax3">.</SPAN><SPAN CLASS="syntax3">do</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">name</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">adjustTableParameters</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax10">&gt;</SPAN>
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">&lt;</SPAN><SPAN CLASS="syntax10">html</SPAN><SPAN CLASS="syntax10">:</SPAN><SPAN CLASS="syntax9">img</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">page</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">/</SPAN><SPAN CLASS="syntax3">images</SPAN><SPAN CLASS="syntax3">/</SPAN><SPAN CLASS="syntax3">adjust</SPAN><SPAN CLASS="syntax3">.</SPAN><SPAN CLASS="syntax3">jpg</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">border</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">0</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax10">/</SPAN><SPAN CLASS="syntax10">&gt;</SPAN><SPAN CLASS="syntax10">&lt;</SPAN><SPAN CLASS="syntax10">/</SPAN><SPAN CLASS="syntax10">html</SPAN><SPAN CLASS="syntax10">:</SPAN><SPAN CLASS="syntax9">link</SPAN><SPAN CLASS="syntax10">&gt;</SPAN>
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>Click<SPAN CLASS="syntax125"> </SPAN>on<SPAN CLASS="syntax125"> </SPAN>the<SPAN CLASS="syntax125"> </SPAN>icon<SPAN CLASS="syntax125"> </SPAN>to<SPAN CLASS="syntax125"> </SPAN>the<SPAN CLASS="syntax125"> </SPAN>left<SPAN CLASS="syntax125"> </SPAN>to<SPAN CLASS="syntax125"> </SPAN>adjust<SPAN CLASS="syntax125"> </SPAN>visibility<SPAN CLASS="syntax125"> </SPAN>and<SPAN CLASS="syntax125"> </SPAN>sort<SPAN CLASS="syntax125"> </SPAN>order<SPAN CLASS="syntax125"> </SPAN>of<SPAN CLASS="syntax125"> </SPAN>the<SPAN CLASS="syntax125"> </SPAN>columns

<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">&lt;</SPAN><SPAN CLASS="syntax10">table</SPAN><SPAN CLASS="syntax10">:</SPAN><SPAN CLASS="syntax9">table</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">id</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">guiCustomersAdjustable</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">name</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">customerListW</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax10">&gt;</SPAN>
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">&lt;</SPAN><SPAN CLASS="syntax10">logic</SPAN><SPAN CLASS="syntax10">:</SPAN><SPAN CLASS="syntax9">iterate</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">id</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">element</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">name</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">customerListW</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax10">&gt;</SPAN>

<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">&lt;</SPAN><SPAN CLASS="syntax10">bean</SPAN><SPAN CLASS="syntax10">:</SPAN><SPAN CLASS="syntax9">define</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">id</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">c_id</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">name</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">element</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">property</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">id</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax10">/</SPAN><SPAN CLASS="syntax10">&gt;</SPAN>
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">&lt;</SPAN><SPAN CLASS="syntax10">bean</SPAN><SPAN CLASS="syntax10">:</SPAN><SPAN CLASS="syntax9">define</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">id</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">c_name</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">name</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">element</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">property</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">name</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax10">/</SPAN><SPAN CLASS="syntax10">&gt;</SPAN>
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">&lt;</SPAN><SPAN CLASS="syntax10">bean</SPAN><SPAN CLASS="syntax10">:</SPAN><SPAN CLASS="syntax9">define</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">id</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">c_conname</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">name</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">element</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">property</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">contactName</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax10">/</SPAN><SPAN CLASS="syntax10">&gt;</SPAN>
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">&lt;</SPAN><SPAN CLASS="syntax10">bean</SPAN><SPAN CLASS="syntax10">:</SPAN><SPAN CLASS="syntax9">define</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">id</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">c_contitle</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">name</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">element</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">property</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">contactTitle</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax10">/</SPAN><SPAN CLASS="syntax10">&gt;</SPAN>
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">&lt;</SPAN><SPAN CLASS="syntax10">table</SPAN><SPAN CLASS="syntax10">:</SPAN><SPAN CLASS="syntax9">define</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">id</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">c_phone</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax10">&gt;</SPAN>
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">&lt;</SPAN><SPAN CLASS="syntax10">bean</SPAN><SPAN CLASS="syntax10">:</SPAN><SPAN CLASS="syntax9">write</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">name</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">element</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">property</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">phone</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax10">/</SPAN><SPAN CLASS="syntax10">&gt;</SPAN>
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">&lt;</SPAN><SPAN CLASS="syntax10">/</SPAN><SPAN CLASS="syntax10">table</SPAN><SPAN CLASS="syntax10">:</SPAN><SPAN CLASS="syntax9">define</SPAN><SPAN CLASS="syntax10">&gt;</SPAN>
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">&lt;</SPAN><SPAN CLASS="syntax10">bean</SPAN><SPAN CLASS="syntax10">:</SPAN><SPAN CLASS="syntax9">define</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">id</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">c_city</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">name</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">element</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">property</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">city</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax10">/</SPAN><SPAN CLASS="syntax10">&gt;</SPAN>
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">&lt;</SPAN><SPAN CLASS="syntax10">bean</SPAN><SPAN CLASS="syntax10">:</SPAN><SPAN CLASS="syntax9">define</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">id</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">c_country</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">name</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">element</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">property</SPAN><SPAN CLASS="syntax10">=</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">country</SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax10">/</SPAN><SPAN CLASS="syntax10">&gt;</SPAN>

<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">&lt;</SPAN><SPAN CLASS="syntax10">table</SPAN><SPAN CLASS="syntax10">:</SPAN><SPAN CLASS="syntax9">tr</SPAN><SPAN CLASS="syntax10">/</SPAN><SPAN CLASS="syntax10">&gt;</SPAN>

<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">&lt;</SPAN><SPAN CLASS="syntax10">/</SPAN><SPAN CLASS="syntax10">logic</SPAN><SPAN CLASS="syntax10">:</SPAN><SPAN CLASS="syntax9">iterate</SPAN><SPAN CLASS="syntax10">&gt;</SPAN>
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax10">&lt;</SPAN><SPAN CLASS="syntax10">/</SPAN><SPAN CLASS="syntax10">table</SPAN><SPAN CLASS="syntax10">:</SPAN><SPAN CLASS="syntax9">table</SPAN><SPAN CLASS="syntax10">&gt;</SPAN>
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>
</PRE>
  </tiles:put>
  
  <tiles:put name="javaConfig" direct="true">
<PRE><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax6">public</SPAN><SPAN CLASS="syntax125"> </SPAN>ActionForward<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax9">execute</SPAN>(
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>ActionMapping<SPAN CLASS="syntax125"> </SPAN>mapping,
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>ActionForm<SPAN CLASS="syntax125"> </SPAN>form,
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>HttpServletRequest<SPAN CLASS="syntax125"> </SPAN>request,
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>HttpServletResponse<SPAN CLASS="syntax125"> </SPAN>response)
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax6">throws</SPAN><SPAN CLASS="syntax125"> </SPAN>Exception<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax11">{</SPAN>

<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>HttpSession<SPAN CLASS="syntax125"> </SPAN>session<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax11">=</SPAN><SPAN CLASS="syntax125"> </SPAN>request.<SPAN CLASS="syntax9">getSession</SPAN>();

<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>DefaultHTMLTable<SPAN CLASS="syntax125"> </SPAN>table<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax11">=</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax6">new</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax9">DefaultHTMLTable</SPAN>();
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>table.<SPAN CLASS="syntax9">setMapping</SPAN>(<SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">fCustomerListAdjustable</SPAN><SPAN CLASS="syntax3">&quot;</SPAN>);
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>table.<SPAN CLASS="syntax9">setLength</SPAN>(<SPAN CLASS="syntax12">10</SPAN>);
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>table.<SPAN CLASS="syntax9">setSortColumn</SPAN>(<SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">id</SPAN><SPAN CLASS="syntax3">&quot;</SPAN>);
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>table.<SPAN CLASS="syntax9">setIsAscending</SPAN>(<SPAN CLASS="syntax4">true</SPAN>);
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>HTMLTableCache<SPAN CLASS="syntax125"> </SPAN>cache<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax11">=</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax6">new</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax9">HTMLTableCache</SPAN>(session,<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">customerListW</SPAN><SPAN CLASS="syntax3">&quot;</SPAN>);
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>cache.<SPAN CLASS="syntax9">updateTable</SPAN>(table);

<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>PersistenceBroker<SPAN CLASS="syntax125"> </SPAN>broker<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax11">=</SPAN><SPAN CLASS="syntax125"> </SPAN>PersistenceBrokerFactory.<SPAN CLASS="syntax9">defaultPersistenceBroker</SPAN>();
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>Criteria<SPAN CLASS="syntax125"> </SPAN>criteria<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax11">=</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax6">new</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax9">Criteria</SPAN>();
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>criteria.<SPAN CLASS="syntax9">addOrderBy</SPAN>(table.<SPAN CLASS="syntax9">getSortColumn</SPAN>(),<SPAN CLASS="syntax125"> </SPAN>table.<SPAN CLASS="syntax9">getIsAscending</SPAN>());
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>Query<SPAN CLASS="syntax125"> </SPAN>query<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax11">=</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax6">new</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax9">QueryByCriteria</SPAN>(Customer.<SPAN CLASS="syntax8">class</SPAN>,<SPAN CLASS="syntax125"> </SPAN>criteria);
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>table.<SPAN CLASS="syntax9">setVolume</SPAN>(broker.<SPAN CLASS="syntax9">getCount</SPAN>(query));
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>query.<SPAN CLASS="syntax9">setStartAtIndex</SPAN>(table.<SPAN CLASS="syntax9">getFrom</SPAN>()<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax11">+</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax12">1</SPAN>);
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>query.<SPAN CLASS="syntax9">setEndAtIndex</SPAN>(table.<SPAN CLASS="syntax9">getFrom</SPAN>()<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax11">+</SPAN><SPAN CLASS="syntax125"> </SPAN>table.<SPAN CLASS="syntax9">getLength</SPAN>()<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax11">+</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax12">1</SPAN>);
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>Collection<SPAN CLASS="syntax125"> </SPAN>customers<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax11">=</SPAN><SPAN CLASS="syntax125"> </SPAN>broker.<SPAN CLASS="syntax9">getCollectionByQuery</SPAN>(query);
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>broker.<SPAN CLASS="syntax9">close</SPAN>();

<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>table.<SPAN CLASS="syntax9">addAll</SPAN>(customers);
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>session.<SPAN CLASS="syntax9">setAttribute</SPAN>(<SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">customerListW</SPAN><SPAN CLASS="syntax3">&quot;</SPAN>,<SPAN CLASS="syntax125"> </SPAN>table);

<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>Map<SPAN CLASS="syntax125"> </SPAN>adjustTableParameters<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax11">=</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax6">new</SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax9">Hashtable</SPAN>();
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>adjustTableParameters.<SPAN CLASS="syntax9">put</SPAN>(<SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">tableID</SPAN><SPAN CLASS="syntax3">&quot;</SPAN>,<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">guiCustomersAdjustable</SPAN><SPAN CLASS="syntax3">&quot;</SPAN>);
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>adjustTableParameters.<SPAN CLASS="syntax9">put</SPAN>(<SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">tableName</SPAN><SPAN CLASS="syntax3">&quot;</SPAN>,<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">customerListW</SPAN><SPAN CLASS="syntax3">&quot;</SPAN>);
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN>session.<SPAN CLASS="syntax9">setAttribute</SPAN>(<SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">adjustTableParameters</SPAN><SPAN CLASS="syntax3">&quot;</SPAN>,<SPAN CLASS="syntax125"> </SPAN>adjustTableParameters);

<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax6">return</SPAN><SPAN CLASS="syntax125"> </SPAN>mapping.<SPAN CLASS="syntax9">findForward</SPAN>(<SPAN CLASS="syntax3">&quot;</SPAN><SPAN CLASS="syntax3">success</SPAN><SPAN CLASS="syntax3">&quot;</SPAN>);
<SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax125"> </SPAN><SPAN CLASS="syntax11">}</SPAN>

</PRE>
  </tiles:put>
  
  <tiles:put name="strutsConfig"/>
  
</tiles:insert>
