/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Sun Jan 18 15:21:12 CST 2009 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.jbpmmanager;

import java.io.Serializable;

/**
 * A class that represents a row in the JBPM_NodeExt table. 
 * You can customize the behavior of this class by editing the class, {@link JbpmNodeext()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractJbpmnodeext 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long nodeid;

   
    /** The value of the simple nodeclass property. */
    private java.lang.String nodeclass;

    /** The value of the simple nodename property. */
    private java.lang.String nodename;

    /** The value of the simple processdefineid property. */
    private java.lang.Long processdefineid;

    /** The value of the simple processdefinename property. */
    private java.lang.String processdefinename;

    /** The value of the simple version property. */
    private java.lang.Integer version;

    /** The value of the simple des property. */
    private java.lang.String des;

    /** The value of the simple orgfilter property. */
    private java.lang.Integer orgfilter;

    /** The value of the simple indfilter property. */
    private java.lang.Integer indfilter;

    /** The value of the simple areafilter property. */
    private java.lang.Integer areafilter;

    /** The value of the simple jumpflag property. */
    private java.lang.Integer jumpflag;

    /** The value of the simple rem1 property. */
    private java.lang.String rem1;

    /** The value of the simple ext1 property. */
    private java.lang.String ext1;

    /** The value of the simple ext2 property. */
    private java.lang.String ext2;

    /** The value of the simple ext3 property. */
    private java.lang.String ext3;

    /** The value of the simple ext4 property. */
    private java.lang.String ext4;

    /** The value of the simple ext5 property. */
    private java.lang.String ext5;

    /**
     * Simple constructor of AbstractJbpmNodeext instances.
     */
    public AbstractJbpmnodeext()
    {
    }

    /**
     * Constructor of AbstractJbpmNodeext instances given a simple primary key.
     * @param nodeid
     */
    public AbstractJbpmnodeext(java.lang.Long nodeid)
    {
        this.setNodeid(nodeid);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getNodeid()
    {
        return nodeid;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param nodeid
     */
    public void setNodeid(java.lang.Long nodeid)
    {
        this.hashValue = 0;
        this.nodeid = nodeid;
    }

    /**
     * Return the value of the NodeClass column.
     * @return java.lang.String
     */
    public java.lang.String getNodeclass()
    {
        return this.nodeclass;
    }

    /**
     * Set the value of the NodeClass column.
     * @param nodeclass
     */
    public void setNodeclass(java.lang.String nodeclass)
    {
        this.nodeclass = nodeclass;
    }

    /**
     * Return the value of the NodeName column.
     * @return java.lang.String
     */
    public java.lang.String getNodename()
    {
        return this.nodename;
    }

    /**
     * Set the value of the NodeName column.
     * @param nodename
     */
    public void setNodename(java.lang.String nodename)
    {
        this.nodename = nodename;
    }

    /**
     * Return the value of the ProcessDefineId column.
     * @return java.lang.Long
     */
    public java.lang.Long getProcessdefineid()
    {
        return this.processdefineid;
    }

    /**
     * Set the value of the ProcessDefineId column.
     * @param processdefineid
     */
    public void setProcessdefineid(java.lang.Long processdefineid)
    {
        this.processdefineid = processdefineid;
    }

    /**
     * Return the value of the ProcessDefineName column.
     * @return java.lang.String
     */
    public java.lang.String getProcessdefinename()
    {
        return this.processdefinename;
    }

    /**
     * Set the value of the ProcessDefineName column.
     * @param processdefinename
     */
    public void setProcessdefinename(java.lang.String processdefinename)
    {
        this.processdefinename = processdefinename;
    }

    /**
     * Return the value of the VERSION column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getVersion()
    {
        return this.version;
    }

    /**
     * Set the value of the VERSION column.
     * @param version
     */
    public void setVersion(java.lang.Integer version)
    {
        this.version = version;
    }

    /**
     * Return the value of the Des column.
     * @return java.lang.String
     */
    public java.lang.String getDes()
    {
        return this.des;
    }

    /**
     * Set the value of the Des column.
     * @param des
     */
    public void setDes(java.lang.String des)
    {
        this.des = des;
    }

    /**
     * Return the value of the OrgFilter column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getOrgfilter()
    {
        return this.orgfilter;
    }

    /**
     * Set the value of the OrgFilter column.
     * @param orgfilter
     */
    public void setOrgfilter(java.lang.Integer orgfilter)
    {
        this.orgfilter = orgfilter;
    }

    /**
     * Return the value of the IndFilter column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getIndfilter()
    {
        return this.indfilter;
    }

    /**
     * Set the value of the IndFilter column.
     * @param indfilter
     */
    public void setIndfilter(java.lang.Integer indfilter)
    {
        this.indfilter = indfilter;
    }

    /**
     * Return the value of the AreaFilter column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getAreafilter()
    {
        return this.areafilter;
    }

    /**
     * Set the value of the AreaFilter column.
     * @param areafilter
     */
    public void setAreafilter(java.lang.Integer areafilter)
    {
        this.areafilter = areafilter;
    }

    /**
     * Return the value of the JumpFlag column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getJumpflag()
    {
        return this.jumpflag;
    }

    /**
     * Set the value of the JumpFlag column.
     * @param jumpflag
     */
    public void setJumpflag(java.lang.Integer jumpflag)
    {
        this.jumpflag = jumpflag;
    }

    /**
     * Return the value of the Rem1 column.
     * @return java.lang.String
     */
    public java.lang.String getRem1()
    {
        return this.rem1;
    }

    /**
     * Set the value of the Rem1 column.
     * @param rem1
     */
    public void setRem1(java.lang.String rem1)
    {
        this.rem1 = rem1;
    }

    /**
     * Return the value of the Ext1 column.
     * @return java.lang.String
     */
    public java.lang.String getExt1()
    {
        return this.ext1;
    }

    /**
     * Set the value of the Ext1 column.
     * @param ext1
     */
    public void setExt1(java.lang.String ext1)
    {
        this.ext1 = ext1;
    }

    /**
     * Return the value of the Ext2 column.
     * @return java.lang.String
     */
    public java.lang.String getExt2()
    {
        return this.ext2;
    }

    /**
     * Set the value of the Ext2 column.
     * @param ext2
     */
    public void setExt2(java.lang.String ext2)
    {
        this.ext2 = ext2;
    }

    /**
     * Return the value of the Ext3 column.
     * @return java.lang.String
     */
    public java.lang.String getExt3()
    {
        return this.ext3;
    }

    /**
     * Set the value of the Ext3 column.
     * @param ext3
     */
    public void setExt3(java.lang.String ext3)
    {
        this.ext3 = ext3;
    }

    /**
     * Return the value of the Ext4 column.
     * @return java.lang.String
     */
    public java.lang.String getExt4()
    {
        return this.ext4;
    }

    /**
     * Set the value of the Ext4 column.
     * @param ext4
     */
    public void setExt4(java.lang.String ext4)
    {
        this.ext4 = ext4;
    }

    /**
     * Return the value of the Ext5 column.
     * @return java.lang.String
     */
    public java.lang.String getExt5()
    {
        return this.ext5;
    }

    /**
     * Set the value of the Ext5 column.
     * @param ext5
     */
    public void setExt5(java.lang.String ext5)
    {
        this.ext5 = ext5;
    }

   
    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Jbpmnodeext))
            return false;
        Jbpmnodeext that = (Jbpmnodeext) rhs;
        if (this.getNodeid() == null || that.getNodeid() == null)
            return false;
        return (this.getNodeid().equals(that.getNodeid()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int nodeidValue = this.getNodeid() == null ? 0 : this.getNodeid().hashCode();
            result = result * 37 + nodeidValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
