/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Sun Jan 18 15:21:59 CST 2009 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.jbpmmanager;

import java.io.Serializable;

/**
 * A class that represents a row in the JBPM_NodeExtTarget table. 
 * You can customize the behavior of this class by editing the class, {@link JbpmNodeexttarget()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractJbpmnodeexttarget 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long actionid;

    /** The value of the jbpmNodeext association. */
    private Long nodeid;

    /** The value of the simple actionname property. */
    private java.lang.String actionname;

    /** The value of the simple des property. */
    private java.lang.String des;

    /** The value of the simple enabledflag property. */
    private java.lang.String enabledflag;

    /** The value of the simple url1 property. */
    private java.lang.String url1;

    /** The value of the simple target1 property. */
    private java.lang.String target1;

    /** The value of the simple param1 property. */
    private java.lang.String param1;

    /** The value of the simple url2 property. */
    private java.lang.String url2;

    /** The value of the simple target2 property. */
    private java.lang.String target2;

    /** The value of the simple param2 property. */
    private java.lang.String param2;

    /** The value of the simple url3 property. */
    private java.lang.String url3;

    /** The value of the simple target3 property. */
    private java.lang.String target3;

    /** The value of the simple param3 property. */
    private java.lang.String param3;

    /** The value of the simple ext1 property. */
    private java.lang.String ext1;

    /** The value of the simple ext2 property. */
    private java.lang.String ext2;

    /** The value of the simple ext3 property. */
    private java.lang.String ext3;

    /** The value of the simple ext4 property. */
    private java.lang.String ext4;

    /** The value of the simple ext5 property. */
    private java.lang.String ext5;

    /**
     * Simple constructor of AbstractJbpmNodeexttarget instances.
     */
    public AbstractJbpmnodeexttarget()
    {
    }

    /**
     * Constructor of AbstractJbpmNodeexttarget instances given a simple primary key.
     * @param actionid
     */
    public AbstractJbpmnodeexttarget(java.lang.Long actionid)
    {
        this.setActionid(actionid);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getActionid()
    {
        return actionid;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param actionid
     */
    public void setActionid(java.lang.Long actionid)
    {
        this.hashValue = 0;
        this.actionid = actionid;
    }

    

    /**
     * Return the value of the ActionName column.
     * @return java.lang.String
     */
    public java.lang.String getActionname()
    {
        return this.actionname;
    }

    /**
     * Set the value of the ActionName column.
     * @param actionname
     */
    public void setActionname(java.lang.String actionname)
    {
        this.actionname = actionname;
    }

    /**
     * Return the value of the Des column.
     * @return java.lang.String
     */
    public java.lang.String getDes()
    {
        return this.des;
    }

    /**
     * Set the value of the Des column.
     * @param des
     */
    public void setDes(java.lang.String des)
    {
        this.des = des;
    }

    /**
     * Return the value of the EnabledFlag column.
     * @return java.lang.String
     */
    public java.lang.String getEnabledflag()
    {
        return this.enabledflag;
    }

    /**
     * Set the value of the EnabledFlag column.
     * @param enabledflag
     */
    public void setEnabledflag(java.lang.String enabledflag)
    {
        this.enabledflag = enabledflag;
    }

    /**
     * Return the value of the Url1 column.
     * @return java.lang.String
     */
    public java.lang.String getUrl1()
    {
        return this.url1;
    }

    /**
     * Set the value of the Url1 column.
     * @param url1
     */
    public void setUrl1(java.lang.String url1)
    {
        this.url1 = url1;
    }

    /**
     * Return the value of the Target1 column.
     * @return java.lang.String
     */
    public java.lang.String getTarget1()
    {
        return this.target1;
    }

    /**
     * Set the value of the Target1 column.
     * @param target1
     */
    public void setTarget1(java.lang.String target1)
    {
        this.target1 = target1;
    }

    /**
     * Return the value of the Param1 column.
     * @return java.lang.String
     */
    public java.lang.String getParam1()
    {
        return this.param1;
    }

    /**
     * Set the value of the Param1 column.
     * @param param1
     */
    public void setParam1(java.lang.String param1)
    {
        this.param1 = param1;
    }

    /**
     * Return the value of the Url2 column.
     * @return java.lang.String
     */
    public java.lang.String getUrl2()
    {
        return this.url2;
    }

    /**
     * Set the value of the Url2 column.
     * @param url2
     */
    public void setUrl2(java.lang.String url2)
    {
        this.url2 = url2;
    }

    /**
     * Return the value of the Target2 column.
     * @return java.lang.String
     */
    public java.lang.String getTarget2()
    {
        return this.target2;
    }

    /**
     * Set the value of the Target2 column.
     * @param target2
     */
    public void setTarget2(java.lang.String target2)
    {
        this.target2 = target2;
    }

    /**
     * Return the value of the Param2 column.
     * @return java.lang.String
     */
    public java.lang.String getParam2()
    {
        return this.param2;
    }

    /**
     * Set the value of the Param2 column.
     * @param param2
     */
    public void setParam2(java.lang.String param2)
    {
        this.param2 = param2;
    }

    /**
     * Return the value of the Url3 column.
     * @return java.lang.String
     */
    public java.lang.String getUrl3()
    {
        return this.url3;
    }

    /**
     * Set the value of the Url3 column.
     * @param url3
     */
    public void setUrl3(java.lang.String url3)
    {
        this.url3 = url3;
    }

    /**
     * Return the value of the Target3 column.
     * @return java.lang.String
     */
    public java.lang.String getTarget3()
    {
        return this.target3;
    }

    /**
     * Set the value of the Target3 column.
     * @param target3
     */
    public void setTarget3(java.lang.String target3)
    {
        this.target3 = target3;
    }

    /**
     * Return the value of the Param3 column.
     * @return java.lang.String
     */
    public java.lang.String getParam3()
    {
        return this.param3;
    }

    /**
     * Set the value of the Param3 column.
     * @param param3
     */
    public void setParam3(java.lang.String param3)
    {
        this.param3 = param3;
    }

    /**
     * Return the value of the Ext1 column.
     * @return java.lang.String
     */
    public java.lang.String getExt1()
    {
        return this.ext1;
    }

    /**
     * Set the value of the Ext1 column.
     * @param ext1
     */
    public void setExt1(java.lang.String ext1)
    {
        this.ext1 = ext1;
    }

    /**
     * Return the value of the Ext2 column.
     * @return java.lang.String
     */
    public java.lang.String getExt2()
    {
        return this.ext2;
    }

    /**
     * Set the value of the Ext2 column.
     * @param ext2
     */
    public void setExt2(java.lang.String ext2)
    {
        this.ext2 = ext2;
    }

    /**
     * Return the value of the Ext3 column.
     * @return java.lang.String
     */
    public java.lang.String getExt3()
    {
        return this.ext3;
    }

    /**
     * Set the value of the Ext3 column.
     * @param ext3
     */
    public void setExt3(java.lang.String ext3)
    {
        this.ext3 = ext3;
    }

    /**
     * Return the value of the Ext4 column.
     * @return java.lang.String
     */
    public java.lang.String getExt4()
    {
        return this.ext4;
    }

    /**
     * Set the value of the Ext4 column.
     * @param ext4
     */
    public void setExt4(java.lang.String ext4)
    {
        this.ext4 = ext4;
    }

    /**
     * Return the value of the Ext5 column.
     * @return java.lang.String
     */
    public java.lang.String getExt5()
    {
        return this.ext5;
    }

    /**
     * Set the value of the Ext5 column.
     * @param ext5
     */
    public void setExt5(java.lang.String ext5)
    {
        this.ext5 = ext5;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Jbpmnodeexttarget))
            return false;
        Jbpmnodeexttarget that = (Jbpmnodeexttarget) rhs;
        if (this.getActionid() == null || that.getActionid() == null)
            return false;
        return (this.getActionid().equals(that.getActionid()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int actionidValue = this.getActionid() == null ? 0 : this.getActionid().hashCode();
            result = result * 37 + actionidValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

	public Long getNodeid() {
		return nodeid;
	}

	public void setNodeid(Long nodeid) {
		this.nodeid = nodeid;
	}
}
