/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Oct 30 10:17:56 CST 2008 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.jbpmmanager;

import java.io.Serializable;

/**
 * A class that represents a row in the JBPMTokenFlow table. 
 * You can customize the behavior of this class by editing the class, {@link Jbpmtokenflow()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractJbpmtokenflow 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long jnl;

    /** The value of the simple taskinstancetoken property. */
    private java.lang.Long taskinstancetoken;

    /** The value of the simple flowver property. */
    private java.lang.String flowver;

    /** The value of the simple r1 property. */
    private java.lang.Long r1;

    /** The value of the simple r2 property. */
    private java.lang.Long r2;

    /** The value of the simple r3 property. */
    private java.lang.String r3;

    /** The value of the simple r4 property. */
    private java.lang.String r4;

    /** The value of the simple r5 property. */
    private java.lang.String r5;

    /**
     * Simple constructor of AbstractJbpmtokenflow instances.
     */
    public AbstractJbpmtokenflow()
    {
    }

    /**
     * Constructor of AbstractJbpmtokenflow instances given a simple primary key.
     * @param jnl
     */
    public AbstractJbpmtokenflow(java.lang.Long jnl)
    {
        this.setJnl(jnl);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getJnl()
    {
        return jnl;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param jnl
     */
    public void setJnl(java.lang.Long jnl)
    {
        this.hashValue = 0;
        this.jnl = jnl;
    }

    /**
     * Return the value of the TaskInstanceToken column.
     * @return java.lang.Long
     */
    public java.lang.Long getTaskinstancetoken()
    {
        return this.taskinstancetoken;
    }

    /**
     * Set the value of the TaskInstanceToken column.
     * @param taskinstancetoken
     */
    public void setTaskinstancetoken(java.lang.Long taskinstancetoken)
    {
        this.taskinstancetoken = taskinstancetoken;
    }

    /**
     * Return the value of the FlowVer column.
     * @return java.lang.String
     */
    public java.lang.String getFlowver()
    {
        return this.flowver;
    }

    /**
     * Set the value of the FlowVer column.
     * @param flowver
     */
    public void setFlowver(java.lang.String flowver)
    {
        this.flowver = flowver;
    }

    /**
     * Return the value of the R1 column.
     * @return java.lang.Long
     */
    public java.lang.Long getR1()
    {
        return this.r1;
    }

    /**
     * Set the value of the R1 column.
     * @param r1
     */
    public void setR1(java.lang.Long r1)
    {
        this.r1 = r1;
    }

    /**
     * Return the value of the R2 column.
     * @return java.lang.Long
     */
    public java.lang.Long getR2()
    {
        return this.r2;
    }

    /**
     * Set the value of the R2 column.
     * @param r2
     */
    public void setR2(java.lang.Long r2)
    {
        this.r2 = r2;
    }

    /**
     * Return the value of the R3 column.
     * @return java.lang.String
     */
    public java.lang.String getR3()
    {
        return this.r3;
    }

    /**
     * Set the value of the R3 column.
     * @param r3
     */
    public void setR3(java.lang.String r3)
    {
        this.r3 = r3;
    }

    /**
     * Return the value of the R4 column.
     * @return java.lang.String
     */
    public java.lang.String getR4()
    {
        return this.r4;
    }

    /**
     * Set the value of the R4 column.
     * @param r4
     */
    public void setR4(java.lang.String r4)
    {
        this.r4 = r4;
    }

    /**
     * Return the value of the R5 column.
     * @return java.lang.String
     */
    public java.lang.String getR5()
    {
        return this.r5;
    }

    /**
     * Set the value of the R5 column.
     * @param r5
     */
    public void setR5(java.lang.String r5)
    {
        this.r5 = r5;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Jbpmtokenflow))
            return false;
        Jbpmtokenflow that = (Jbpmtokenflow) rhs;
        if (this.getJnl() == null || that.getJnl() == null)
            return false;
        return (this.getJnl().equals(that.getJnl()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int jnlValue = this.getJnl() == null ? 0 : this.getJnl().hashCode();
            result = result * 37 + jnlValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
