/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Sun Jan 18 15:21:59 CST 2009 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.jbpmmanager;

import java.io.Serializable;

/**
 * A class that represents a row in the Jbpm_DecisionJump table. 
 * You can customize the behavior of this class by editing the class, {@link JbpmDecisionjump()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractJbpmdecisionjump 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer jnl;

    /** The value of the jbpmNodeext association. */
    private Long nodeid;

    /** The value of the simple flag property. */
    private java.lang.Integer flag;

    /** The value of the simple selpath property. */
    private java.lang.String selpath;

    /** The value of the simple minqty property. */
    private java.lang.Double minqty;

    /** The value of the simple maxqty property. */
    private java.lang.Double maxqty;

    /** The value of the simple tranpath property. */
    private java.lang.String tranpath;

    /** The value of the simple ext1 property. */
    private java.lang.String ext1;

    /** The value of the simple ext2 property. */
    private java.lang.String ext2;

    /** The value of the simple ext3 property. */
    private java.lang.String ext3;

    /** The value of the simple ext4 property. */
    private java.lang.String ext4;

    /** The value of the simple ext5 property. */
    private java.lang.String ext5;

    /** The value of the simple ext6 property. */
    private java.lang.Double ext6;

    /** The value of the simple ext7 property. */
    private java.lang.Double ext7;

    /** The value of the simple ext8 property. */
    private java.lang.Double ext8;

    /** The value of the simple ext9 property. */
    private java.lang.Double ext9;

    /** The value of the simple ext10 property. */
    private java.lang.Double ext10;

    /**
     * Simple constructor of AbstractJbpmDecisionjump instances.
     */
    public AbstractJbpmdecisionjump()
    {
    }

    /**
     * Constructor of AbstractJbpmDecisionjump instances given a simple primary key.
     * @param jnl
     */
    public AbstractJbpmdecisionjump(java.lang.Integer jnl)
    {
        this.setJnl(jnl);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Integer
     */
    public java.lang.Integer getJnl()
    {
        return jnl;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param jnl
     */
    public void setJnl(java.lang.Integer jnl)
    {
        this.hashValue = 0;
        this.jnl = jnl;
    }

   

    /**
     * Return the value of the Flag column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getFlag()
    {
        return this.flag;
    }

    /**
     * Set the value of the Flag column.
     * @param flag
     */
    public void setFlag(java.lang.Integer flag)
    {
        this.flag = flag;
    }

    /**
     * Return the value of the SelPath column.
     * @return java.lang.String
     */
    public java.lang.String getSelpath()
    {
        return this.selpath;
    }

    /**
     * Set the value of the SelPath column.
     * @param selpath
     */
    public void setSelpath(java.lang.String selpath)
    {
        this.selpath = selpath;
    }

    /**
     * Return the value of the MinQty column.
     * @return java.lang.Double
     */
    public java.lang.Double getMinqty()
    {
        return this.minqty;
    }

    /**
     * Set the value of the MinQty column.
     * @param minqty
     */
    public void setMinqty(java.lang.Double minqty)
    {
        this.minqty = minqty;
    }

    /**
     * Return the value of the MaxQty column.
     * @return java.lang.Double
     */
    public java.lang.Double getMaxqty()
    {
        return this.maxqty;
    }

    /**
     * Set the value of the MaxQty column.
     * @param maxqty
     */
    public void setMaxqty(java.lang.Double maxqty)
    {
        this.maxqty = maxqty;
    }

    /**
     * Return the value of the TranPath column.
     * @return java.lang.String
     */
    public java.lang.String getTranpath()
    {
        return this.tranpath;
    }

    /**
     * Set the value of the TranPath column.
     * @param tranpath
     */
    public void setTranpath(java.lang.String tranpath)
    {
        this.tranpath = tranpath;
    }

    /**
     * Return the value of the Ext1 column.
     * @return java.lang.String
     */
    public java.lang.String getExt1()
    {
        return this.ext1;
    }

    /**
     * Set the value of the Ext1 column.
     * @param ext1
     */
    public void setExt1(java.lang.String ext1)
    {
        this.ext1 = ext1;
    }

    /**
     * Return the value of the Ext2 column.
     * @return java.lang.String
     */
    public java.lang.String getExt2()
    {
        return this.ext2;
    }

    /**
     * Set the value of the Ext2 column.
     * @param ext2
     */
    public void setExt2(java.lang.String ext2)
    {
        this.ext2 = ext2;
    }

    /**
     * Return the value of the Ext3 column.
     * @return java.lang.String
     */
    public java.lang.String getExt3()
    {
        return this.ext3;
    }

    /**
     * Set the value of the Ext3 column.
     * @param ext3
     */
    public void setExt3(java.lang.String ext3)
    {
        this.ext3 = ext3;
    }

    /**
     * Return the value of the Ext4 column.
     * @return java.lang.String
     */
    public java.lang.String getExt4()
    {
        return this.ext4;
    }

    /**
     * Set the value of the Ext4 column.
     * @param ext4
     */
    public void setExt4(java.lang.String ext4)
    {
        this.ext4 = ext4;
    }

    /**
     * Return the value of the Ext5 column.
     * @return java.lang.String
     */
    public java.lang.String getExt5()
    {
        return this.ext5;
    }

    /**
     * Set the value of the Ext5 column.
     * @param ext5
     */
    public void setExt5(java.lang.String ext5)
    {
        this.ext5 = ext5;
    }

    /**
     * Return the value of the Ext6 column.
     * @return java.lang.Double
     */
    public java.lang.Double getExt6()
    {
        return this.ext6;
    }

    /**
     * Set the value of the Ext6 column.
     * @param ext6
     */
    public void setExt6(java.lang.Double ext6)
    {
        this.ext6 = ext6;
    }

    /**
     * Return the value of the Ext7 column.
     * @return java.lang.Double
     */
    public java.lang.Double getExt7()
    {
        return this.ext7;
    }

    /**
     * Set the value of the Ext7 column.
     * @param ext7
     */
    public void setExt7(java.lang.Double ext7)
    {
        this.ext7 = ext7;
    }

    /**
     * Return the value of the Ext8 column.
     * @return java.lang.Double
     */
    public java.lang.Double getExt8()
    {
        return this.ext8;
    }

    /**
     * Set the value of the Ext8 column.
     * @param ext8
     */
    public void setExt8(java.lang.Double ext8)
    {
        this.ext8 = ext8;
    }

    /**
     * Return the value of the Ext9 column.
     * @return java.lang.Double
     */
    public java.lang.Double getExt9()
    {
        return this.ext9;
    }

    /**
     * Set the value of the Ext9 column.
     * @param ext9
     */
    public void setExt9(java.lang.Double ext9)
    {
        this.ext9 = ext9;
    }

    /**
     * Return the value of the Ext10 column.
     * @return java.lang.Double
     */
    public java.lang.Double getExt10()
    {
        return this.ext10;
    }

    /**
     * Set the value of the Ext10 column.
     * @param ext10
     */
    public void setExt10(java.lang.Double ext10)
    {
        this.ext10 = ext10;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Jbpmdecisionjump))
            return false;
        Jbpmdecisionjump that = (Jbpmdecisionjump) rhs;
        if (this.getJnl() == null || that.getJnl() == null)
            return false;
        return (this.getJnl().equals(that.getJnl()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int jnlValue = this.getJnl() == null ? 0 : this.getJnl().hashCode();
            result = result * 37 + jnlValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

	public Long getNodeid() {
		return nodeid;
	}

	public void setNodeid(Long nodeid) {
		this.nodeid = nodeid;
	}
}
