/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Sun Jan 18 15:21:58 CST 2009 by MyEclipse Hibernate Tool.
 */
package com.gzunicorn.hibernate.jbpmmanager;

import java.io.Serializable;

/**
 * A class that represents a row in the JBPM_NodeExtActors table. 
 * You can customize the behavior of this class by editing the class, {@link JbpmNodeextactors()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractJbpmnodeextactors 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long id;

    /** The value of the jbpmNodeext association. */
    private Long nodeid;

    /** The value of the simple actors property. */
    private java.lang.String actors;

    /** The value of the simple typeid property. */
    private java.lang.Integer typeid;

    /** The value of the simple tableid property. */
    private java.lang.Integer tableid;

    /** The value of the simple ext1 property. */
    private java.lang.String ext1;

    /** The value of the simple ext2 property. */
    private java.lang.String ext2;

    /** The value of the simple ext3 property. */
    private java.lang.String ext3;

    /** The value of the simple ext4 property. */
    private java.lang.String ext4;

    /** The value of the simple ext5 property. */
    private java.lang.String ext5;

    /**
     * Simple constructor of AbstractJbpmNodeextactors instances.
     */
    public AbstractJbpmnodeextactors()
    {
    }

    /**
     * Constructor of AbstractJbpmNodeextactors instances given a simple primary key.
     * @param id
     */
    public AbstractJbpmnodeextactors(java.lang.Long id)
    {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Long id)
    {
        this.hashValue = 0;
        this.id = id;
    }

   

    /**
     * Return the value of the Actors column.
     * @return java.lang.String
     */
    public java.lang.String getActors()
    {
        return this.actors;
    }

    /**
     * Set the value of the Actors column.
     * @param actors
     */
    public void setActors(java.lang.String actors)
    {
        this.actors = actors;
    }

    /**
     * Return the value of the TypeId column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getTypeid()
    {
        return this.typeid;
    }

    /**
     * Set the value of the TypeId column.
     * @param typeid
     */
    public void setTypeid(java.lang.Integer typeid)
    {
        this.typeid = typeid;
    }

    /**
     * Return the value of the TableId column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getTableid()
    {
        return this.tableid;
    }

    /**
     * Set the value of the TableId column.
     * @param tableid
     */
    public void setTableid(java.lang.Integer tableid)
    {
        this.tableid = tableid;
    }

    /**
     * Return the value of the Ext1 column.
     * @return java.lang.String
     */
    public java.lang.String getExt1()
    {
        return this.ext1;
    }

    /**
     * Set the value of the Ext1 column.
     * @param ext1
     */
    public void setExt1(java.lang.String ext1)
    {
        this.ext1 = ext1;
    }

    /**
     * Return the value of the Ext2 column.
     * @return java.lang.String
     */
    public java.lang.String getExt2()
    {
        return this.ext2;
    }

    /**
     * Set the value of the Ext2 column.
     * @param ext2
     */
    public void setExt2(java.lang.String ext2)
    {
        this.ext2 = ext2;
    }

    /**
     * Return the value of the Ext3 column.
     * @return java.lang.String
     */
    public java.lang.String getExt3()
    {
        return this.ext3;
    }

    /**
     * Set the value of the Ext3 column.
     * @param ext3
     */
    public void setExt3(java.lang.String ext3)
    {
        this.ext3 = ext3;
    }

    /**
     * Return the value of the Ext4 column.
     * @return java.lang.String
     */
    public java.lang.String getExt4()
    {
        return this.ext4;
    }

    /**
     * Set the value of the Ext4 column.
     * @param ext4
     */
    public void setExt4(java.lang.String ext4)
    {
        this.ext4 = ext4;
    }

    /**
     * Return the value of the Ext5 column.
     * @return java.lang.String
     */
    public java.lang.String getExt5()
    {
        return this.ext5;
    }

    /**
     * Set the value of the Ext5 column.
     * @param ext5
     */
    public void setExt5(java.lang.String ext5)
    {
        this.ext5 = ext5;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Jbpmnodeextactors))
            return false;
        Jbpmnodeextactors that = (Jbpmnodeextactors) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

	public Long getNodeid() {
		return nodeid;
	}

	public void setNodeid(Long nodeid) {
		this.nodeid = nodeid;
	}
}
